server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - fr-CA
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    manager:
        name: TinyDB
        connection: /pygeoapi/data/processes.db
        output_dir: /pygeoapi/data/

logging:
    level: ERROR

metadata:
    identification:
        title: "@ogcapi-js test instance"
        description: ogc api instance for @ogcapi-js e2e tests
        keywords:
            - ogc
            - js
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://haoliangyu.github.io/ogcapi-js/
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://haoliangyu.github.io/ogcapi-js/
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact


resources:
    hello-world:
        type: process
        links: []
        processor:
            name: HelloWorld

    vineyards:
        type: collection
        title: Vineyards
        description: Vineyards
        keywords: vineyards
        links: []
        extents:
            spatial:
                bbox: [6.302134844793972, 49.00870173627915, 8.417903391872795, 50.61389348807117]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2022-07-04T00:00:00Z
                end: 2022-07-04T00:00:00Z
        providers:
            - type: feature
              name: GeoJSON
              data: /pygeoapi/data/vineyards.geojson
              id_field: id