name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    services:
      pygeoapi:
        image: "ghcr.io/haoliangyu/ogcapi-js:master"
        options: >-
          --health-cmd "curl http://localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5000:80"
    steps:
    - uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Unit test
      run: npm test
    - name: E2E test
      run: npm run test:e2e
    - name: Build doc
      run: npm run build:doc

  automerge-dependabot-pr:
    if: ${{ github.event_name == 'pull_request' }}
    needs:
      - main
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
