name: master-push

on:
  push:
    branches: [ master ]

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build:doc
    - name: deploy doc
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.DOC_DEPLOY_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: install dependencies
      run: npm install
    - name: test
      run: npm run test:e2e

