name: update-docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build doc
      run: npm run build:doc
    - name: Deploy doc
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc